I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/main_room.rpy", line 14, in script
    b "Back here again..."
Exception: Sayer 'b' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/main_room.rpy", line 14, in script
    b "Back here again..."
  File "D:\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'b' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
GAME NAME HERE 1.0
Sat Apr  1 23:43:11 2023
